### ISSUE TITLE
Party candidate list is inconsistent with constituency page

### ISSUE THREAD

**Issue by gerv** [mysociety/yournextrepresentative#303]
https://yournextmp.com/party/party%3A17/english-democrats says "No candidate in Dartford".

https://yournextmp.com/constituency/66011/dartford says Steve Uncles is standing (which is the truth; he's their election coordinator).

Gerv

**Comment by gerv** [comment]
Also true of Louise Dutton, standing in Don Valley.

**Comment by mhl** [comment]
@gerv This is fixed now, after fixing some bad data that meant Elasticsearch wasn't indexing some people. Please reopen this if you spot other cases...

**Comment by redpandanat** [comment]
I think that this may be an issue still. e.g. https://yournextmp.com/party/party%3A63/green-party Although Darren Hall standing in Bristol West it is listed as no candidate.
The party candidate counts may well be correct. https://yournextmp.com/numbers/parties
Candidates per constituency is not correct. https://yournextmp.com/numbers/constituencies e.g. Glenrothes should be 4 but is only listed as 3. https://yournextmp.com/constituency/14432/glenrothes

**Comment by gerv** [comment]
mhl said: please reopen if you spot other cases. However, I don't appear to have the power to do that...

**Comment by mhl** [comment]
These issues are all fixed now, thanks for the bug reports.
